language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install . --quiet
  - pip install nose --quiet
  - pip install speaklater --quiet
  - pip install flake8 --quiet

before_script:
  - "python -V 2>&1 | grep -qF 'Python 2.6' || flake8 ."

script:
  - nosetests

branches:
  only:
    - master
